### ISSUE TITLE
ajaxuploadAllowOverwrite enabled causing php timeout error

### ISSUE THREAD

**Issue by travisbotello** [Jako/AjaxUpload#30]
When a file with the same name exists in the upload folder AjaxUpload appends a `_1` to the uploaded file when `ajaxuploadAllowOverwrite` is set to `false`. For example:

Upload download.jpg
- download.jpg

Upload download.jpg again
- download_1.jpg

When `download.jpg` is uploaded a third time this results in an error and the php script times out.

**Comment by travisbotello** [comment]
Sorry about that....I can't reproduce this when using regular form submission. This is only causing issues when using ajax form processing. Seems like the error is caused by my ajax setup. 

However when enabling `ajaxuploadAllowOverwrite` I am seeing the same php execution time out error:

```
[[!FormIt?
    &hooks=`AjaxUpload2Formit`
    &ajaxuploadFieldname=`image`
    &ajaxuploadTarget=`image-cache/uploads`
    &ajaxuploadUid=`image`
    &ajaxuploadAllowOverwrite=`1`
]]
<form method="post" action=[[~[[*id]]]]>
[[!AjaxUpload?
    &uid=`image`
    &allowedExtensions=`jpg,jpeg,png,gif`
    &thumbX=`75`
    &thumbY=`75`
]]
<input type="submit" value="abschicken">
</form>
```

**Comment by Jako** [comment]
What kind of ajax solution do you use?

**Comment by travisbotello** [comment]
In frontend I am using vue.js with axios and then processing server-side via MODx resource with an empty template and a formit snippet call. Working quiet well. But as I said I was able to reproduce the issue with a non-ajax form submission. Either setting `&ajaxuploadClearQueue` to true or setting  `ajaxuploadAllowOverwrite` to true is causing the php timeout error...looks like there is a problem.

**Comment by Jako** [comment]
Please create the AjaxUpload call before the FormIt call. If I am right, this should solve the issue.

**Comment by travisbotello** [comment]
I tried that and changed the order, but it is still not working.

**Comment by matdave** [comment]
Any update on this, it looks like we are getting the same error reported.

**Comment by matdave** [comment]
I take that back, I actually had to add the setting ``` &ajaxuploadAllowOverwrite=`1` ``` in order for the uploads to stop timing out.

**Comment by tsteinketopspot** [comment]
I tried adding `&ajaxuploadAllowOverwrite=`1`` but it did not seem to fix our issue.  This issue occurs when uploading a file for the third time regardless if this setting is turned on or not, and may only occur with slower internet connections.  In the mean time I am going to try rolling back to a previous version.  Thanks.

**Comment by travisbotello** [comment]
I bypassed the issue by adding an additional formit hook that renames/moves the file to a different location after uploading.

**Comment by Jako** [comment]
This should be fixed with the 1.5.7 release.
